### PR TITLE
Remove unnecessary srchash parameters from Provision and ActionDriver

### PR DESCRIPTION
**Pull request by jyn514**
These were never used.

### CODE REVIEW

**Comment by kentonv** [comment]
Wait... is ekam today computing a hash of every file? Does removing this improve performance?

I'm sure my intent was to eventually use the hashes to implement caching, where Ekam could avoid re-running a rule if the inputs were exactly the same as last time. This seems like an important component of incremental builds, which I thought was your goal... So are you sure you want to remove this code?

**Comment by jyn514** [comment]
> Wait... is ekam today computing a hash of every file? Does removing this improve performance?

Yes, it is hashing each file unnecessarily. I would expect this to improve performance but I haven't done any measurements.

> This seems like an important component of incremental builds, which I thought was your goal... So are you sure you want to remove this code?

I'm not sure exactly when and where I'll need the hash, but it's also easy to add back if I need it - if I wrote this code myself I would only hash it in ActionDriver rather than computing it earlier. So I don't think keeping the code around just because it's already written is very useful.

(If it helps, I originally made this PR while trying to serialize the whole in-memory graph of objects, which we discussed is a bad idea. But I still think this is a useful cleanup even discounting that.)

**Comment by jyn514** [comment]
> I'm not sure exactly when and where I'll need the hash, but it's also easy to add back if I need it

For the same reason, this only removes places where I *compute* the hash, it doesn't remove `contentHash` altogether.

**Comment by kentonv** [comment]
I'm a little uncomfortable removing this if we're going to re-introduce hashing immediately anyway, as I trust past-me probably had the best idea of where the hashing should occur, and I don't want to lose that info, as current-me definitely doesn't know the answer anymore. If it turns out that hashing should be done somewhere else, I'd hope to see a single change in the future that moves it from this location to the new location, so we can think about whether that's the right change... rather than have two separate changes separated in time such that we forget want past-me had written.

All that said, if there is a significant performance win from disabling hashing here, that's another story.

**Comment by jyn514** [comment]
:+1: makes sense to me, I'll close this until I've figured out where I think hashing _should_ happen and we can compare that to where it happens now.

**Pull request closed without merging**
